=== SergioValcarcePRO/vscod/XML/EXAMEN DTD/examen.dtd
<!ELEMENT impresoras (impresora+)>
<!ELEMENT impresora (marca ,modelo ,peso ,tamano+ ,cartucho ,enred*)>
<!ATTLIST impresora numSerie ID #REQUIRED>
<!ATTLIST impresora tipo (matricial|laser|tinta) #REQUIRED>
<!ATTLIST impresora compra NMTOKEN #IMPLIED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT tamano (#PCDATA)>
<!ELEMENT cartucho (#PCDATA)>
<!ELEMENT enred EMPTY>

=== SergioValcarcePRO/vscod/XML/EXAMEN DTD/examen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE impresoras SYSTEM "examen.dtd">
<impresoras>
    <impresora numSerie="i245" tipo="laser" compra="2024">
        <marca>Epson</marca>
        <modelo>EPL300</modelo>
        <peso>4.52</peso>
        <tamano>A4</tamano>
        <cartucho>C-123BV</cartucho>
        <enred />
    </impresora>
</impresoras>
